### ISSUE TITLE
DE between subtypes

### ISSUE THREAD

**Issue by FaezeK** [STAT540-UBC/Repo_team_TeamSix_2021W2#87]
Top 10 genes DE between CMS1 and other groups
"PPIAL4B"   "CYP4X1"    "TCN1"      "PDZD3"     "ASRGL1"    "C6orf130"  "NGEF"      "LOC728613" "TYSND1"  "GSTM1"

Top 10 genes DE between CMS2 and other groups
"PDZD3"  "NUCB1"  "FRMD1"  "SCD5"   "BAMBI"  "GPR160" "NGEF"   "TMEM44" "ZNF23"  "CDHR1"

Top 10 genes DE between CMS3 and other groups
"NDUFA4L2" "CSPG4"    "PAIP2B"   "SEPT5"    "SERAC1"   "RTN4IP1"  "FGFR1OP"  "PEX3"     "FIG4"     "C6orf203"

Top 10 genes DE between CMS4 and other groups
"GPR107"   "BCL2L2"   "GOLGA5"   "YY1"      "ZNF200"   "ZC3H14"   "GIMAP2"   "KIAA1737" "FCF1"     "ZNF16"

Top 10 genes DE between None and other groups
"MCOLN2"  "HMGXB4"  "LRIG1"   "TMEM69"  "MTFMT"   "TMEM222" "OMA1"    "ZFY"     "MFHAS1"  "POLR2J2"

Heatmap of the above genes
<img width="1010" alt="Screen Shot 2021-04-03 at 12 20 38 PM" src="https://user-images.githubusercontent.com/11761806/113489111-07559380-9477-11eb-8d07-c02ea63b65b3.png">

Same heatmap ordered by CMS subtypes
<img width="1011" alt="Screen Shot 2021-04-03 at 12 20 03 PM" src="https://user-images.githubusercontent.com/11761806/113489118-14728280-9477-11eb-91fc-07ffb262fef3.png">

**Comment by FaezeK** [comment]
The heatmaps show a clear effect from batch! This just makes me think that maybe we should go back to Wilcoxon test and correction by ComBat instead of ComBat_seq. Wilcoxon didn't change the distribution of our p-values, but at least it accepts negative values and we can take care of batch effects with ComBat.

**Comment by creisle** [comment]
seems like it would be worth a shot at least

**Comment by creisle** [comment]
how are you calculating the top10 genes btw? this model included batch as a covariate right?

**Comment by FaezeK** [comment]
yeah the model has batch as a factor

**Comment by FaezeK** [comment]
Adding the library sizes to DE analysis helped with the results, but you can still see the effects of batch

Top 10 genes DE between CMS1 and other groups
"TRIB2"  "ASPHD2" "CIITA"  "AXIN2"  "USP18"  "WARS"   "DUSP4"  "HSPA4L" "RNF43"  "TYMS"

Top 10 genes DE between CMS2 and other groups
"SLC5A6"   "TP53RK"   "PIGU"     "NECAB3"   "UQCC"     "MOCS3"    "POFUT1"   "CDK5RAP1" "TRIB2"    "TH1L"

Top 10 genes DE between CMS3 and other groups
"B3GNT6"   "HEPACAM2" "SPINK4"   "ATOH1"    "CAPN9"    "CHST5"    "NEURL"    "SPDEF"    "GPR120"   "FABP2"

Top 10 genes DE between CMS4 and other groups
"BOC"    "EVC"    "GEFT"   "TGFB3"  "COL8A2" "CLIP3"  "SSC5D"  "JAM3"   "STON1"  "NTM"

Top 10 genes DE between None and other groups
"SDR16C5"  "B3GALT5"  "EXT2"     "C3orf39"  "ACPL2"    "KAL1"     "COL17A1"  "C6orf105" "C1orf21"  "MUC17"

Heatmap of the above genes
<img width="1012" alt="Screen Shot 2021-04-03 at 5 14 54 PM" src="https://user-images.githubusercontent.com/11761806/113494916-d8084c00-94a1-11eb-8439-9b12b1cf61b0.png">

Same heatmap ordered by CMS subtypes
<img width="1010" alt="Screen Shot 2021-04-03 at 5 22 05 PM" src="https://user-images.githubusercontent.com/11761806/113494918-e3f40e00-94a1-11eb-9ad4-c0c4a833286c.png">

**Comment by FaezeK** [comment]
Although, ComBat mixed the data points pretty well
<img width="477" alt="Screen Shot 2021-04-03 at 7 20 15 PM" src="https://user-images.githubusercontent.com/11761806/113496763-c5960e80-94b1-11eb-9573-0001d34fcaee.png">

The effects of batches are very visible
<img width="1006" alt="Screen Shot 2021-04-03 at 7 19 14 PM" src="https://user-images.githubusercontent.com/11761806/113496771-d47cc100-94b1-11eb-9c99-9fbff6264d03.png">

Ordered heatmap
<img width="1007" alt="Screen Shot 2021-04-03 at 7 19 39 PM" src="https://user-images.githubusercontent.com/11761806/113496772-dd6d9280-94b1-11eb-9449-25a4109c5773.png">

**Comment by creisle** [comment]
Do you think that it is impacted b/c we don't batch correct before we pass to the subtype caller? does that process involve any sort of batch correction?

**Comment by FaezeK** [comment]
Top genes found with Wilcoxon test:
Top 10 genes DE between CMS1 and other groups
"TRIB2"   "SHROOM4" "PLAGL2"  "ETV5"    "DUSP4"   "ASPHD2"  "TYMS"    "USP18"   "POFUT1"  "RNF43"

Top 10 genes DE between CMS2 and other groups
"SLC5A6" "ASCL2"  "PLAGL2" "POFUT1" "TP53RK" "ANO9"   "PIGU"   "AHCY"   "TH1L"   "RNF43"

Top 10 genes DE between CMS3 and other groups
"RCN3"    "TIMP3"   "RAB3IL1" "CERCAM"  "KCNAB2"  "MFAP2"   "HTRA1"   "RBMS1"   "MFRP"    "MXRA8"

Top 10 genes DE between CMS4 and other groups
"BGN"     "MXRA8"   "SPARC"   "ISLR"    "THY1"    "AEBP1"   "CTHRC1"  "TIMP2"   "EFEMP2"  "OLFML2B"

Top 10 genes DE between None and other groups
"C3orf39" "COL17A1" "KLHL29"  "MYO7A"   "SUSD3"   "FHDC1"   "GZMB"    "RHPN1"   "NUP210"  "A4GALT"

**Comment by FaezeK** [comment]
> Do you think that it is impacted b/c we don't batch correct before we pass to the subtype caller? does that process involve any sort of batch correction?

We do batch correct with ComBat before calling the subtypes

**Comment by creisle** [comment]
> We do batch correction with ComBat before calling the subtypes

Oh! never mind then. I thought the Random Forests model took the data prior to batch correction and lowly expressed gene filtering

**Comment by FaezeK** [comment]
> > We do batch correction with ComBat before calling the subtypes
> 
> Oh! never mind then. I thought the Random Forests model took the data prior to batch correction and lowly expressed gene filtering

Oh no, it's after both batch correction and gene filtering

**Comment by creisle** [comment]
btw this is what the DE analysis looks like if you nix the GA data

![image](https://user-images.githubusercontent.com/4342641/113618326-5ed93800-960c-11eb-8ac3-d4df306bbacf.png)

**Comment by FaezeK** [comment]
It has a very similar pattern to the mixed heatmap if you visually remove the GA

**Comment by creisle** [comment]
Ya i think diff genes tho?

**Comment by FaezeK** [comment]
Absolutely, it makes sense to get different genes when working with different datasets, but there are overlaps which is good

**Comment by FaezeK** [comment]
I was looking at the heatmaps generated for TvN and subtypes and it seemed like the batch effect was more visible in DE analysis btw subtypes compared to TvN, so I took a look at the codes to see what could cause the issue and I noticed that Rhiannon found the z-scores of log2CPM values while I was looking at z-scores of raw counts (the matrix that we fed into limma::voom). So, I made another heatmap with z-scores of log2CPM:
<img width="1069" alt="Screen Shot 2021-04-05 at 5 13 58 PM" src="https://user-images.githubusercontent.com/11761806/113641649-ecc81980-9632-11eb-999d-454dffa8a35d.png">

**Comment by FaezeK** [comment]
Although the input to limma::voom is raw counts, it converts them to log2CPM, so I think I'm gonna update my code to generate the heatmaps of log2CPM to match it with TvN heatmap.

**Comment by creisle** [comment]
that actually looks quite a bit better! if we want the zscores to be more comparable we should use the same colors/caps. So either @cmrn-rhi match the zscore cut offs @FaezeK used, or @FaezeK use the color scheme i put in the TN one? 

Note: with a pref-define color scheme you don't need the cutoffs

**Comment by creisle** [comment]
what does that plot look like with col clustering?

**Comment by FaezeK** [comment]
The batches are mixed with col clustering
<img width="1068" alt="Screen Shot 2021-04-05 at 5 22 19 PM" src="https://user-images.githubusercontent.com/11761806/113641960-8abbe400-9633-11eb-9a4b-724d37844241.png">

**Comment by FaezeK** [comment]
Since I'm gonna change my script, I'll also add the same colors as TvN
